// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// Cfits_read_img
Rcpp::NumericMatrix Cfits_read_img(Rcpp::String filename, int xpix, int ypix, int ext);
RcppExport SEXP _Rfits_Cfits_read_img(SEXP filenameSEXP, SEXP xpixSEXP, SEXP ypixSEXP, SEXP extSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::String >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< int >::type xpix(xpixSEXP);
    Rcpp::traits::input_parameter< int >::type ypix(ypixSEXP);
    Rcpp::traits::input_parameter< int >::type ext(extSEXP);
    rcpp_result_gen = Rcpp::wrap(Cfits_read_img(filename, xpix, ypix, ext));
    return rcpp_result_gen;
END_RCPP
}
// Cfits_read_col
RcppExport SEXP Cfits_read_col(Rcpp::String filename, int colref, int ext);
RcppExport SEXP _Rfits_Cfits_read_col(SEXP filenameSEXP, SEXP colrefSEXP, SEXP extSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::String >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< int >::type colref(colrefSEXP);
    Rcpp::traits::input_parameter< int >::type ext(extSEXP);
    rcpp_result_gen = Rcpp::wrap(Cfits_read_col(filename, colref, ext));
    return rcpp_result_gen;
END_RCPP
}
// Cfits_read_nrow
int Cfits_read_nrow(Rcpp::String filename, int ext);
RcppExport SEXP _Rfits_Cfits_read_nrow(SEXP filenameSEXP, SEXP extSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::String >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< int >::type ext(extSEXP);
    rcpp_result_gen = Rcpp::wrap(Cfits_read_nrow(filename, ext));
    return rcpp_result_gen;
END_RCPP
}
// Cfits_read_ncol
int Cfits_read_ncol(Rcpp::String filename, int ext);
RcppExport SEXP _Rfits_Cfits_read_ncol(SEXP filenameSEXP, SEXP extSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::String >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< int >::type ext(extSEXP);
    rcpp_result_gen = Rcpp::wrap(Cfits_read_ncol(filename, ext));
    return rcpp_result_gen;
END_RCPP
}
// Cfits_read_colname
SEXP Cfits_read_colname(Rcpp::String filename, int colref, int ext);
RcppExport SEXP _Rfits_Cfits_read_colname(SEXP filenameSEXP, SEXP colrefSEXP, SEXP extSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::String >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< int >::type colref(colrefSEXP);
    Rcpp::traits::input_parameter< int >::type ext(extSEXP);
    rcpp_result_gen = Rcpp::wrap(Cfits_read_colname(filename, colref, ext));
    return rcpp_result_gen;
END_RCPP
}
// Cfits_create_bintable
void Cfits_create_bintable(Rcpp::String filename, int tfields, Rcpp::CharacterVector ttypes, Rcpp::CharacterVector tforms, Rcpp::CharacterVector tunits, Rcpp::String extname);
RcppExport SEXP _Rfits_Cfits_create_bintable(SEXP filenameSEXP, SEXP tfieldsSEXP, SEXP ttypesSEXP, SEXP tformsSEXP, SEXP tunitsSEXP, SEXP extnameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::String >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< int >::type tfields(tfieldsSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type ttypes(ttypesSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type tforms(tformsSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type tunits(tunitsSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type extname(extnameSEXP);
    Cfits_create_bintable(filename, tfields, ttypes, tforms, tunits, extname);
    return R_NilValue;
END_RCPP
}
// Cfits_write_col
void Cfits_write_col(Rcpp::String filename, SEXP data, int nrow, int colref, int ext, int typecode);
RcppExport SEXP _Rfits_Cfits_write_col(SEXP filenameSEXP, SEXP dataSEXP, SEXP nrowSEXP, SEXP colrefSEXP, SEXP extSEXP, SEXP typecodeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::String >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type colref(colrefSEXP);
    Rcpp::traits::input_parameter< int >::type ext(extSEXP);
    Rcpp::traits::input_parameter< int >::type typecode(typecodeSEXP);
    Cfits_write_col(filename, data, nrow, colref, ext, typecode);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Rfits_Cfits_read_img", (DL_FUNC) &_Rfits_Cfits_read_img, 4},
    {"_Rfits_Cfits_read_col", (DL_FUNC) &_Rfits_Cfits_read_col, 3},
    {"_Rfits_Cfits_read_nrow", (DL_FUNC) &_Rfits_Cfits_read_nrow, 2},
    {"_Rfits_Cfits_read_ncol", (DL_FUNC) &_Rfits_Cfits_read_ncol, 2},
    {"_Rfits_Cfits_read_colname", (DL_FUNC) &_Rfits_Cfits_read_colname, 3},
    {"_Rfits_Cfits_create_bintable", (DL_FUNC) &_Rfits_Cfits_create_bintable, 6},
    {"_Rfits_Cfits_write_col", (DL_FUNC) &_Rfits_Cfits_write_col, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_Rfits(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
