# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rffrtnm <- function(url, rootname) {
    .Call(`_Rfits_Rffrtnm`, url, rootname)
}

Rfits_read_img <- function(filename, xpix = 100L, ypix = 100L) {
    .Call(`_Rfits_Rfits_read_img`, filename, xpix, ypix)
}

rfits_read_col <- function(filename, column, cwidth, hdu) {
    .Call(`_Rfits_rfits_read_col`, filename, column, cwidth, hdu)
}

