# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Cfits_read_col <- function(filename, colref = 1L, ext = 2L) {
    .Call(`_Rfits_Cfits_read_col`, filename, colref, ext)
}

Cfits_read_nrow <- function(filename, ext = 2L) {
    .Call(`_Rfits_Cfits_read_nrow`, filename, ext)
}

Cfits_read_nhdu <- function(filename) {
    .Call(`_Rfits_Cfits_read_nhdu`, filename)
}

Cfits_read_ncol <- function(filename, ext = 2L) {
    .Call(`_Rfits_Cfits_read_ncol`, filename, ext)
}

Cfits_read_colname <- function(filename, colref = 1L, ext = 2L) {
    .Call(`_Rfits_Cfits_read_colname`, filename, colref, ext)
}

Cfits_create_bintable <- function(filename, tfields, ttypes, tforms, tunits, extname, ext = 2L, create_ext = 1L, create_file = 1L, table_type = 2L) {
    invisible(.Call(`_Rfits_Cfits_create_bintable`, filename, tfields, ttypes, tforms, tunits, extname, ext, create_ext, create_file, table_type))
}

Cfits_write_col <- function(filename, data, nrow, colref = 1L, ext = 2L, typecode = 1L) {
    invisible(.Call(`_Rfits_Cfits_write_col`, filename, data, nrow, colref, ext, typecode))
}

Cfits_read_key <- function(filename, keyname, typecode, ext = 1L) {
    .Call(`_Rfits_Cfits_read_key`, filename, keyname, typecode, ext)
}

Cfits_update_key <- function(filename, keyvalue, keyname, keycomment, ext = 1L, typecode = 1L) {
    invisible(.Call(`_Rfits_Cfits_update_key`, filename, keyvalue, keyname, keycomment, ext, typecode))
}

Cfits_write_history <- function(filename, history, ext = 1L) {
    invisible(.Call(`_Rfits_Cfits_write_history`, filename, history, ext))
}

Cfits_write_comment <- function(filename, comment, ext = 1L) {
    invisible(.Call(`_Rfits_Cfits_write_comment`, filename, comment, ext))
}

Cfits_write_date <- function(filename, ext = 1L) {
    invisible(.Call(`_Rfits_Cfits_write_date`, filename, ext))
}

Cfits_create_image <- function(filename, bitpix = 32L, naxis1 = 100L, naxis2 = 100L) {
    invisible(.Call(`_Rfits_Cfits_create_image`, filename, bitpix, naxis1, naxis2))
}

Cfits_read_img <- function(filename, naxis1 = 100L, naxis2 = 100L, ext = 1L, datatype = -32L) {
    .Call(`_Rfits_Cfits_read_img`, filename, naxis1, naxis2, ext, datatype)
}

Cfits_write_image <- function(filename, data, datatype, naxis1, naxis2, ext = 1L, create_ext = 1L, create_file = 1L, bitpix = 32L) {
    invisible(.Call(`_Rfits_Cfits_write_image`, filename, data, datatype, naxis1, naxis2, ext, create_ext, create_file, bitpix))
}

Cfits_read_header <- function(filename, ext = 1L) {
    .Call(`_Rfits_Cfits_read_header`, filename, ext)
}

Cfits_delete_HDU <- function(filename, ext = 1L) {
    invisible(.Call(`_Rfits_Cfits_delete_HDU`, filename, ext))
}

Cfits_delete_key <- function(filename, keyname, ext = 1L) {
    invisible(.Call(`_Rfits_Cfits_delete_key`, filename, keyname, ext))
}

Cfits_delete_header <- function(filename, ext = 1L) {
    invisible(.Call(`_Rfits_Cfits_delete_header`, filename, ext))
}

Cfits_read_img_subset <- function(filename, fpixel0 = 1L, fpixel1 = 1L, lpixel0 = 100L, lpixel1 = 100L, ext = 1L, datatype = -32L) {
    .Call(`_Rfits_Cfits_read_img_subset`, filename, fpixel0, fpixel1, lpixel0, lpixel1, ext, datatype)
}

